# =============================================================
# PLAY 1 — Rollback serveur web
# =============================================================
- name: Rollback serveur web
  hosts: webservers
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Remettre la page par défaut
      copy:
        content: "<h1>Rollback effectué</h1>"
        dest: /var/www/html/index.html

    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
